# Generated by Django 4.1.1 on 2022-10-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expname', models.CharField(max_length=20)),
                ('expense', models.IntegerField(verbose_name=20)),
            ],
        ),
    ]
