# Generated by Django 4.1.1 on 2022-10-27 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expapp', '0002_balance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Balance',
            new_name='Balence',
        ),
    ]
