# Generated by Django 4.1.1 on 2022-10-27 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expapp', '0003_rename_balance_balence'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Balence',
            new_name='Balance',
        ),
    ]
